# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: setup yarn
        run: |
          npm install -g yarn
          yarn
      - name: build vite website
        run: |
          yarn build
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          commit-message: "deploy latest site "
          clean: true # Automatically remove deleted files from the deploy branch
